"""The per-symbol page: the bear case that must never be optional.

A page assembled from the same data as the buy case is only worth reading if it
also reports what argues *against* it. :func:`risks` is generated by rule for
exactly that reason — a written bear case gets skipped on the names where it is
least convenient — so most of this file checks that each rule fires off the
number it claims to, and that an absent number produces silence rather than a
reassuring zero.
"""

import math

import pytest

from tradingagents.live import charting, deepdive
from tradingagents.live.deepdive import Bars, SymbolAnalysis, render_page, risks
from tradingagents.live.fundamentals import Fundamentals, Quarter
from tradingagents.live.zhnames import ZhNames


def bars(symbol="AAA", n=260, start=60.0, step=0.15, amp=0.03, period=17,
         volume=800_000.0):
    closes = [round((start + step * i) * (1 + amp * math.sin(i * 2 * math.pi / period)), 4)
              for i in range(n)]
    return Bars(symbol=symbol,
                dates=[f"2026-{1 + i % 12:02d}-{1 + i % 28:02d}" for i in range(n)],
                opens=list(closes),
                highs=[c * 1.015 for c in closes],
                lows=[c * 0.985 for c in closes],
                closes=closes,
                volumes=[volume] * n)


class Snap:
    def __init__(self, **kw):
        self.price = kw.get("price", 100.0)
        self.atr_pct = kw.get("atr_pct", 0.02)
        self.rsi14 = kw.get("rsi14", 55.0)
        self.vol_ratio = kw.get("vol_ratio", 1.1)
        self.ret_1m = kw.get("ret_1m", 0.05)
        self.ret_3m = kw.get("ret_3m", 0.18)


class Rec:
    symbol = "AAA"
    reference_price = 100.0
    initial_stop_price = 94.0
    stop_price = 94.0
    target_price = 118.0
    limit_price = 100.30
    shares = 160
    horizon_days = 30
    catalyst = "rank #3 on the nasdaq screen"
    catalyst_url = ""
    catalyst_source = ""
    catalyst_at = ""

    def planned_r(self):
        return 3.0

    def risk_per_share(self):
        return 6.0


class Earnings:
    error = ""
    next_date = "2026-09-12"
    last_date = "2026-06-10"
    surprise_pct = 4.2

    def __init__(self, days=8.0):
        self._days = days

    def days_to_next(self, ref=None):
        return self._days

    def reports_within(self, days, ref=None):
        return self._days <= days


class News:
    def __init__(self, title, lean="neutral", materiality=8, link="", source="Wire"):
        self.title, self.lean, self.materiality = title, lean, materiality
        self.link, self.source, self.ticker = link, source, "AAA"
        self.published = ""

    def age_hours(self, now=None):
        return 3.0


def analysis(**kw):
    b = kw.pop("bars", None) or bars()
    snap = kw.pop("snap", None) or Snap()
    a = SymbolAnalysis(symbol="AAA", zh=ZhNames(overrides={}).get("AAA", "A Company"),
                       roles=["buy"], sector="Technology", bars=b, snap=snap)
    a.trend = deepdive.build_trend(b, snap)
    for k, v in kw.items():
        setattr(a, k, v)
    return a


# ---------------------------------------------------------------------------
# bars
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestBars:
    def test_a_short_history_is_not_ok_to_read(self):
        assert not bars(n=20).ok and bars(n=40).ok

    def test_the_facts_mapping_carries_what_the_horizon_modules_ask_for(self):
        got = bars().facts()
        for key in ("price", "sma200", "ret_12m", "off_high", "atr", "atr_pct",
                    "prev_high", "prev_low", "vol_ratio", "dollar_vol", "spark"):
            assert key in got

    def test_a_return_longer_than_the_history_is_absent_not_zero(self):
        assert math.isnan(bars(n=40).ret(252))

    def test_an_empty_frame_produces_empty_bars_rather_than_raising(self):
        got = deepdive.load_bars("AAA", "2026-08-31", loader=lambda s, d: None)
        assert len(got) == 0 and not got.ok

    def test_a_loader_that_raises_costs_the_bars_not_the_run(self):
        def boom(symbol, when):
            raise RuntimeError("network")

        assert len(deepdive.load_bars("AAA", "2026-08-31", loader=boom)) == 0


# ---------------------------------------------------------------------------
# the arithmetic
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestLevelRead:
    def test_the_break_even_win_rate_is_derived_and_printed(self):
        lines = " ".join(deepdive.level_read(analysis(rec=Rec()), 100_000.0))
        assert "1/(1+R)" in lines and "25%" in lines

    def test_the_risk_is_stated_in_dollars_and_in_percent_of_equity(self):
        lines = " ".join(deepdive.level_read(analysis(rec=Rec()), 100_000.0))
        assert "$960" in lines and "0.96%" in lines

    def test_the_stop_distance_is_expressed_in_atrs_as_well_as_percent(self):
        lines = " ".join(deepdive.level_read(analysis(rec=Rec()), 100_000.0))
        assert "6.0%" in lines and "2 个 ATR" in lines

    def test_a_page_with_no_recommendation_has_no_arithmetic_section(self):
        assert deepdive.level_read(analysis()) == []

    def test_the_stop_is_placed_against_the_nearest_swing_low(self):
        a = analysis(rec=Rec())
        lines = " ".join(deepdive.level_read(a, 100_000.0))
        assert "止损与结构的关系" in lines


# ---------------------------------------------------------------------------
# the bear case
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestRisks:
    def test_silence_is_reported_as_silence_not_as_safety(self):
        """"No risks found" must not read as "no risk"."""
        out = risks(analysis())
        assert len(out) == 1 and "这台机器读到的东西里没有" in out[0]

    def test_a_downtrend_is_named(self):
        falling = bars(start=120.0, step=-0.25)
        out = risks(analysis(bars=falling))
        assert any("下降结构" in r or "跌破" in r or "空头" in r for r in out)

    def test_earnings_inside_the_horizon_is_always_raised(self):
        out = risks(analysis(rec=Rec(), earnings=Earnings(days=8.0)))
        assert any("财报" in r and "穿过止损" in r for r in out)

    def test_earnings_outside_the_horizon_is_not_raised(self):
        out = risks(analysis(rec=Rec(), earnings=Earnings(days=90.0)))
        assert not any("穿过止损" in r for r in out)

    def test_an_unprofitable_company_is_named_as_one(self):
        f = Fundamentals(symbol="AAA", eps_trailing=-0.8)
        assert any("尚未盈利" in r for r in risks(analysis(fundamentals=f)))

    def test_negative_free_cash_flow_is_named(self):
        f = Fundamentals(symbol="AAA", eps_trailing=1.0, free_cashflow=-2.0e8)
        assert any("自由现金流为负" in r for r in risks(analysis(fundamentals=f)))

    def test_a_price_above_the_consensus_target_is_named(self):
        f = Fundamentals(symbol="AAA", eps_trailing=1.0, target_mean=50.0,
                         analysts=12.0)
        out = risks(analysis(fundamentals=f))
        assert any("高于卖方目标价均值" in r for r in out)

    def test_a_target_range_wider_than_its_mean_is_called_out_as_no_consensus(self):
        f = Fundamentals(symbol="AAA", eps_trailing=1.0, target_mean=100.0,
                         target_low=40.0, target_high=200.0, analysts=12.0)
        assert any("分歧极大" in r for r in risks(analysis(fundamentals=f)))

    def test_a_thin_book_is_named_because_the_report_assumed_it_could_fill(self):
        thin = bars(volume=20_000.0)
        assert any("流动性偏薄" in r for r in risks(analysis(bars=thin)))

    def test_a_bearish_headline_is_quoted_with_its_source(self):
        item = News("Company halts trial", lean="bearish", materiality=9)
        out = risks(analysis(news=[item]))
        assert any("Company halts trial" in r and "Wire" in r for r in out)

    def test_a_bearish_but_immaterial_headline_is_not_promoted_to_a_risk(self):
        item = News("Fund trims stake", lean="bearish", materiality=3)
        assert not any("Fund trims stake" in r for r in risks(analysis(news=[item])))


# ---------------------------------------------------------------------------
# the page
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestRenderPage:
    def page(self, **kw):
        return render_page(analysis(**kw), report_date="2026-09-02",
                           data_date="2026-08-31", account_value=100_000.0,
                           back_link="../2026-09-02.md")

    def test_every_section_the_docstring_promises_is_present(self):
        text = self.page(rec=Rec())
        for heading in ("一、价格与图形", "二、这笔交易的算术", "四、消息面",
                        "五、反方观点与风险", "六、原始数据", "七、自己去查"):
            assert f"## {heading}" in text

    def test_the_chart_carries_the_three_levels_of_the_trade(self):
        text = self.page(rec=Rec())
        assert "← 止损" in text and "← 目标" in text and "← 参考" in text

    def test_the_bear_case_is_never_omitted(self):
        assert "## 五、反方观点与风险" in self.page()

    def test_the_two_sessions_are_both_named(self):
        text = self.page()
        assert "2026-08-31 收盘 → 面向 2026-09-02 开盘" in text

    def test_the_page_links_back_to_the_daily_report(self):
        assert "(../2026-09-02.md)" in self.page()

    def test_a_symbol_with_no_history_renders_an_absence_not_an_empty_chart(self):
        text = render_page(SymbolAnalysis(symbol="ZZZ"), report_date="2026-09-02")
        assert "没有价格数据" in text and "```text" not in text

    def test_the_raw_ohlcv_the_page_computed_from_is_printed(self):
        text = self.page()
        assert "| 日期 | 开 | 高 | 低 | 收 | 涨跌 | 成交量 |" in text

    def test_the_cost_matches_the_price_the_order_would_fill_at(self):
        """The daily table prices at the limit; two pages must not disagree."""
        text = self.page(rec=Rec())
        assert f"${Rec.limit_price * Rec.shares:,.2f}" in text

    def test_the_chart_read_says_out_loud_that_it_is_lagging(self):
        assert "滞后指标" in self.page()

    def test_news_items_are_linked_dated_and_sourced(self):
        text = self.page(news=[News("Something happened", link="https://x.test/a")])
        assert "[Something happened](https://x.test/a)" in text
        assert "3h 前" in text and "Wire" in text

    def test_no_news_is_reported_as_a_state_rather_than_left_blank(self):
        assert "没有消息本身也是一种状态" in self.page()
